spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: root
    password: skillyha656
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
